# -*- coding: utf-8 -*-
"""fraud team.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-OUw_uOVDkKoiYMDJfI_pNEZ4nU7msEE

# PROYECTO FINAL JUNIOR SCHOOL
**Luis Alex Farfan**
"""

import numpy as np
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score
from sklearn.neighbors import LocalOutlierFactor
import time
import missingno as msno
from sklearn.impute import KNNImputer 
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import mutual_info_regression

"""## Carga de datos"""

dataset = pd.read_csv('insurance_claims.csv',na_values='?')

#dataset =dataset_df.drop(['policy_number','policy_bind_date','incident_location','incident_date','auto_model','auto_year','insured_hobbies','insured_occupation','auto_make', '_c39'],axis=1)
dataset

dataset['fraud_reported']=dataset['fraud_reported'].apply(lambda x:1 if x=='Y' else 0)
dataset

"""###Histogramas de los datos"""

#Dibujamos histograma
dataset.hist(bins=30, figsize=(20,20),color='c')

"""Podemos observar como hay algunas variables que se distribuyen de manera aproximada a una distribución normal por ejemplo "age" o "total_claim_amount". Adicionalmente, se verifica que nuestro conjunto de datos, es un conjunto desbalanceado ya que nuestra variable a predecir "fraud_reported" tiene muchos más casos donde "frad_reported" es no (0) respecto a los casos dónde sí hay fraude (1).

## Limpieza de datos

###Eliminación de columnas repetidas y duplicadas

Vamos a hacer un análisis previo para buscar posibles columnas duplicadas y también para hallar posibles columnas superfluas que no aporten información a nuestro problema. Para ello empezamos creando una tabla para ver cuantos registros diferentes tiene cada columna.
"""

#Mostrar columnas con sus diferentes valores

print(dataset.nunique(dropna=False).sort_values(ascending=False))

print('Dimensión original del dataframe: {}'.format(dataset.shape))
# Guardamos el número único de valores para cada columna en una variable
counts = dataset.nunique(dropna=False)
# Almacenamos las columnas a borrar
to_del = [i for i,v in enumerate(counts) if v == 1]
print('Columnas a borrar: {}'.format(to_del))
# Borramos las columnas innecesarias
dataset.drop(dataset.columns[to_del], axis=1, inplace=True)
print('Dimensión final del dataframe: {}'.format(dataset.shape))
dataset

"""Observamos si existe algún registro duplicado en nuestro dataset."""

# Calculamos los duplicados
dups = dataset.duplicated()
#dups me devuelve serie con false,false,false,false...false

# Miramos si hay duplicados
print('Algun duplicado? {}'.format(dups.any()))
# Sacamos la lista de duplicados
print('Registros duplicados: \n{}'.format(dataset[dups]))

#Borramos registros duplicados
print('Dimensión original del dataframe: {}'.format(dataset.shape))
# delete duplicate rows
dataset.drop_duplicates(inplace=True)
print('Dimensión final del dataframe: {}'.format(dataset.shape))

"""En la tabla donde salen ordenadas las columnas en función del número de elementos diferentes por columna, se puede observar como hay variables que no aportan información a nuestro estudio ya que aportan un dato diferente para cada registro. Estas columnas son policy_number, insured_zip,policy_bind_date y incident_location. Por otra parte incident_date solo cuenta con fechas correspondientes a enero y febrero y por lo tanto al no estar distribuida por todos los meses, tampoco aporta información. Por esta razón resulta conveniente eliminarlas antes de continuar con las siguientes etapas."""

#Eliminar algunas columnas superfluas en base al nunique de antes
dataset=dataset.drop(['policy_number','policy_bind_date','insured_zip','incident_location','incident_date'],axis=1)
dataset.shape 
#incident date -reclasificar 

#Columnas superfluas policy_number, policy_bind_date,incident_location,incident_date,auto_model,auto_year,insured_hobbies, insured_occupation,auto_make
#dataset=dataset_df5.drop(['policy_number','policy_bind_date','incident_location','incident_date','auto_model','auto_year','insured_hobbies','insured_occupation','auto_make'],axis=1)

"""### Missing data

Antes de eliminar o imputar los missing values de este dataset, se han analizado usando la librería missingno.

En primer lugar se ha obtenido una matriz para visualizar la presencia de los missing values. De esta forma se puede determinar si existe algún patrón en la aparición de estos valores en distintas variables. 

En este caso se ha podido observar como solo se tienen missing values en tres variables: collision_type, property_damage y police_report. No siguen un patrón similar en ningúno de los casos:
"""

msno.matrix(dataset)

"""A continuación se ha obtenido un gráfico de barras con el número de missing values de cada variable. De esta forma se ha podido confirmar que estos valores tan solo aparecen en las tres variables esmentadas anteriormente, con unos 200-400 missing values cada una."""

msno.bar(dataset)

"""Finalmente se ha visualizado el heatmap de las variables que contienen missing values, para determinar si existe alguna correlación en estos valores.

Como se puede observar a continuación, los missing values de estas variables no estan correlados.
"""

msno.heatmap(dataset)

"""### Conversión valores categóricos

Para realizar la imputación de los missing values se han convertido los valores categóricos a numéricos.
"""

#distingim les columnes categoriques de les columnes numeriques
le_count = 0
categorie_count=0
categorical_columns=[]
name_columns=[]
numerical_columns=[]
name_columns_numerical=[]
# iterem en totes les columnes
for col in dataset:
    if dataset[col].dtype == 'object':
        # obtenim una llista amb l'index de totes les columnes categoriques
        categorical_columns.append(dataset.columns.get_loc(col))
        name_columns.append(col)
        categorie_count=categorie_count+dataset[col].nunique()
        le_count += 1
    else:
        # obtenim una llista amb l'index de totes les columnes numeriques
        numerical_columns.append(dataset.columns.get_loc(col))
        name_columns_numerical.append(col)


#Dataset amb columnes categoriques
X_cat= dataset[name_columns]
#dataset amb columnes numèriques
X_numerical=dataset.drop(labels=name_columns,axis=1)

#passem les variables categoriques a numèriques i ajuntem els dos datasets
Encoder=OrdinalEncoder()
Encoder.fit(X_cat)
X_cat=Encoder.transform(X_cat)

X_cat=pd.DataFrame(X_cat)


X_all=pd.concat([X_cat,X_numerical],axis=1)
#y=X_all['fraud_reported']
#X_all=X_all.drop(['fraud_reported'], axis=1)

"""### Eliminación missing values
El siguiente paso ha sido el de determinar el efecto de eliminar los missing values del dataset. Al hacerlo se ha podido observar que se pierde mucha información, ya que se eliminan muchas columnas, así pues, no sería un método demasiado recomendado. Por lo tanto, en vista de que no es lo mejor eliminar los datos, en la siguiente parte analizaremos que métodos de imputación son los más adecuados para nuestro dataset.
"""

X2 = X_all.copy()
X2.isna().sum()

print('Dimension con nan: {}'.format(X2.shape))

X2.dropna(inplace=True)
# summarize the shape of the data with missing rows removed
print('Dimension sin nan: {}'.format(X2.shape))

"""### Imputación
Se han analizado diferentes métodos de imputación para escoger el más adecuado. Para determinarlo, se ha comparado la precisión y tiempo de ejecución de cada metodología.

#### Imputación estadística
"""

data = X_all.values
X, y = data[:, 0:-1], data[:, -1]
# Evaluamos las diferentes estrategias
results = []
finalresults = []
times = []
finaltimes = []
imputations = []
strategies = ['mean', 'median', 'most_frequent', 'constant']

for s in strategies:
    imputations.append(s)
    # Creamos la pipeline
    start = time.time()
    pipeline = Pipeline(steps=[('i', SimpleImputer(strategy=s)), ('m', RandomForestClassifier())])
    # Evaluamos el modelo
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
    # Almacenamos los resultados y el tiempo de ejecución
    results.append(scores)
    end = time.time()
    final_time = end-start
    times.append(final_time)
    finalresults.append(scores)
    finaltimes.append(final_time)
    print('Modelo {}: Media - {:.3f} ; Desviacion - {:.3f} : Tiempo - {} '.format(s, np.mean(scores), np.std(scores), final_time))
# Dibujamos las bondad del modelo y el tiempo de ejecución para comparar
pyplot.boxplot(results, labels=strategies, showmeans=True)
pyplot.show()
pyplot.plot(strategies, times, 'ro')
pyplot.show()

"""#### Imputación con KNNImputer"""

# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, 0:-1], data[:, -1]
# Establecemos las estrategias de vecinos
results = []
times = []
strategies = [str(i) for i in [1,3,5,7,9,15,18,21]]

for s in strategies:
    name = 'knn ' + s
    imputations.append(name)
    start = time.time()
    # Creamos el modelo pipeline
    pipeline = Pipeline(steps=[('i', KNNImputer(n_neighbors=int(s))), ('m',
    RandomForestClassifier())])
    # Evaluamos el modelo
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
    end = time.time()
    final_time = end-start
    # Almacenamos los resultados y el tiempo de ejecución
    results.append(scores)
    times.append(final_time)
    finalresults.append(scores)
    finaltimes.append(final_time)
    print('Estrategia {} vecinos: Media - {:.3f} ({:.3f}) Tiempo {}'.format(s, np.mean(scores), np.std(scores), final_time))
# Dibujamos los resultados y el tiempo de ejecución
pyplot.boxplot(results, labels=strategies, showmeans=True)
pyplot.show()
pyplot.plot(strategies, times, 'ro')
pyplot.show()

"""#### Imputación iterativa"""

# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, 0:-1], data[:, -1]
# Evaluamos las diferentes estrategias
results = []
times = []
strategies = ['ascending', 'descending', 'roman', 'arabic', 'random']
for s in strategies:
    name = 'iterative ' + s
    imputations.append(name)
    start = time.time()
    # Creamos el pipeline
    pipeline = Pipeline(steps=[('i', IterativeImputer(imputation_order=s)), ('m', RandomForestClassifier())])
    # Evaluamos el model
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
    end = time.time()
    final_time = end-start
    # Almacenamos los resultados y el tiempo de ejecución
    results.append(scores)
    times.append(final_time)
    finalresults.append(scores)
    finaltimes.append(final_time)  
    print('Estrategia {} - {:.3f} ({:.3f} Tiempo {})'.format(s, np.mean(scores), np.std(scores), final_time))
# Dibujamos los datos de la comparativa
pyplot.boxplot(results, labels=strategies, showmeans=True)
pyplot.show()
pyplot.plot(strategies, times, 'ro')
pyplot.show()

"""Finalmente se pueden comparar todos los métodos analizados en los siguientes gráficos:"""

for i in range(len(imputations)):
    print('Modelo {}: Media - {:.3f} ; Desviacion - {:.3f} : Tiempo - {} '.format(imputations[i], np.mean(finalresults[i]), np.std(finalresults[i]), finaltimes[i]))

pyplot.boxplot(finalresults, labels=imputations, showmeans=True)
pyplot.title('Comparativa precisión')
pyplot.xticks(rotation=90)
pyplot.show()
pyplot.plot(imputations, finaltimes, 'ro')
pyplot.title('Tiempos de ejecución')
pyplot.xticks(rotation=90)
pyplot.show()

"""En vista del gráfico que compara los distintos métodos de imputación, se puede concluir que en nuestro caso, el mejor método para imputar es el de KNN Imputer con k=3 vecinos. Por lo, tanto será ese método el que se usará de manera predeterminada para imputar los Nan.

Se aplica el método de imputación más indicado y se separa en training set y test set el dataset.
"""

# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]

# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)

# Se separa el trainig set y el test set 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

# Se escalan los resultados
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
  
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

X_df=pd.DataFrame(X)
X_df

"""###Matriz de correlación

Vamos a presentar la matriz de correlación para analizar un poco más en detalle los datos.
"""

correlation = X_numerical.corr()
f, ax = pyplot.subplots(figsize=(20,20))
sns.heatmap(correlation, annot=True)

"""Se puede observar que en la matriz de correlación existen parejas de columnas que están altamente correlacionadas. Concretamente, son* month_as_a_customer* con *age* y *total_claim* con *vehicle_claim*. Mediante esta observación, podríamos quedarnos solamente con la columna de cada pareja que esté más correlacionada con fraud report.

A continuación, se dividen las variables independientes y la etiqueta
"""

# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]

# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)

X_new=np.delete(X,[18,28], axis=1)
# Se separa el trainig set y el test set 
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.33, random_state=1)

# Se escalan los resultados
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
  
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

#Apliquem un RandomForest
model = RandomForestClassifier()
# Entrenem el model
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
#mirem la precisió
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_test, y_test, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

#mirem la confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True)

"""##Extracción de características (RFE,PCA y SVD).

En esta fase veremos brevemente unos métodos de extracción de características.

### RFE para clasificación
"""

#RFE 

import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

# Creamos la pipeline
rfe = RFE(estimator=DecisionTreeClassifier(), n_features_to_select=5)
model = DecisionTreeClassifier()
pipeline = Pipeline(steps=[('s',rfe),('m',model)])
# Evaluamos el modelo
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(pipeline, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
# Presentamos la precision del modelo
print('Precision:{:.3f} ({:.3f})'.format(np.mean(n_scores), np.std(n_scores)))

import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.datasets import make_classification


# Create the RFE object and compute a cross-validated score.

# The "accuracy" scoring shows the proportion of correct classifications

min_features_to_select = 1  # Minimum number of features to consider
rfecv = RFECV(
    estimator=DecisionTreeClassifier(),
    step=1,
    cv=StratifiedKFold(2),
    scoring="accuracy",
    min_features_to_select=min_features_to_select,
)
rfecv.fit(X_train, y_train)

print("Optimal number of features : %d" % rfecv.n_features_)

# Plot number of features VS. cross-validation scores
plt.figure()
plt.xlabel("Number of features selected")
plt.ylabel("Cross validation score (accuracy)")
plt.plot(
    range(min_features_to_select, len(rfecv.grid_scores_) + min_features_to_select),
    rfecv.grid_scores_,
)
plt.show()
rfecv.ranking_

X_train.shape
X_train2=X_train[[5,9,12,27,28,30]]
X_train2
X_test2=X_test[[5,9,12,27,28,30]]

"""### PCA y SVD"""

#PCA
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression


# Definimos la pipeline
steps = [('pca', PCA(n_components=10)), ('m', LogisticRegression())]
model = Pipeline(steps=steps)
# Evaluamos el modelo
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
# Sacamos la precision
#Amb 10 components
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

#Variància acumulada per cada n de components

# Definimos la pipeline
pca = PCA(svd_solver='full')
# Aplicamos el modelo
pca.fit(X_train)
# Sacamos la información del modelo
acc = 0
for i, (val, var) in enumerate(zip(pca.singular_values_, pca.explained_variance_ratio_)):
    acc += var * 100
    print(f'Componente: {i} - Singular value :{val:.4f} - Varianza explicada: {var*100:.4f} % - Acumulada: {acc:.4f} %')

#SVD

from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression

# Definimos el pipeline
steps = [('svd', TruncatedSVD(n_components=10)), ('m', LogisticRegression())]
model = Pipeline(steps=steps)
# Evaluamos el modelo
#Sacamos precisión
#Amb 10 components
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

# Definimos la pipeline
svd = TruncatedSVD(n_components=30)
# Aplicamos el modelo
svd.fit(X_train)
# Sacamos la información del modelo
acc = 0
for i, (val, var) in enumerate(zip(svd.singular_values_, svd.explained_variance_ratio_)):
    acc += var * 100
    print(f'Componente: {i} - Singular value :{val:.4f} - Varianza explicada: {var*100:.4f} % - Acumulada: {acc:.4f} %')

"""##Selección de variables

En este apartado del modelo, seleccionamos las columnas de X_train que luego utilizaremos para mejorar la precisión. Esta selección se hará en función del método que nos de un mejor resultado.

### Categóricas

#### Estadístico chi-2

Donde se puede observar como las variables con una mayor dependencia a la etiqueta son la 9 y la 13.
"""

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from matplotlib import pyplot


# Seleccionamos las variables
def select_features(X_train, y_train, X_test):
    fs = SelectKBest(score_func=chi2, k='all')
    fs.fit(X_train, y_train)
    X_train_fs = fs.transform(X_train)
    X_test_fs = fs.transform(X_test)
    return X_train_fs, X_test_fs, fs


def knn_imputation(X, n):
    # Dividimos las variables independientes y la etiqueta
    # data = df.values
    # Definimos el imputer
    imputer = KNNImputer(n_neighbors = int(n))
    # Entrenamos sobre el dataset
    imputer.fit(X)
    # Transformamos el dataset
    Xtrans = imputer.transform(X)
    return Xtrans

# Realizamos el cálculo solo en las variables categóricas
X_cat_n = knn_imputation(X_cat, 3)

X_train_cat, X_test_cat, y_train_cat, y_test_cat = train_test_split(X_cat_n, y, test_size=0.33, random_state=1)
scaler = MinMaxScaler()
scaler.fit(X_train_cat)
X_train_cat = scaler.transform(X_train_cat)
X_test_cat = scaler.transform(X_test_cat)

# Seleccionamos las variables
X_train_fs, X_test_fs, fs = select_features(X_train_cat, y_train_cat, X_test_cat)
# Puntuamos las variables para su selección
for i in range(len(fs.scores_)):
    print('Variable {}: {}'.format(i, fs.scores_[i]))
# Dibujamos los scores
pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
pyplot.show()

"""#### Estadístico de información mutua

Devuelve el grado de dependencia entre las variables y la variable etiqueta. En este caso las más dependientes han sido la 5 y la 9.
"""

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif

# Seleccionamos las variables
def select_features(X_train, y_train, X_test):
    fs = SelectKBest(score_func=mutual_info_classif, k='all')
    fs.fit(X_train, y_train)
    X_train_fs = fs.transform(X_train)
    X_test_fs = fs.transform(X_test)
    return X_train_fs, X_test_fs, fs

# Seleccionamos las variables
X_train_fs, X_test_fs, fs = select_features(X_train_cat, y_train_cat, X_test_cat)
# Puntuamos las variables para su selección
for i in range(len(fs.scores_)):
    print('Variable {}: {}'.format(i, fs.scores_[i]))
# Dibujamos los scores
pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
pyplot.show()

"""Observando los resultados de estas dos técnicas se han determinado aquellas variables menos dependientes de la variable de salida. A continuación se ha analizado el efecto que tendría en la predicción el borrado de estas variables:"""

from xgboost import XGBClassifier

delete = [0, 3, 4, 6, 8, 12, 14, [0, 3, 8, 12], [8, 12, 14], [0, 3, 6, 8, 12, 14], [0, 3, 4, 6, 8, 12, 14]]
# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]

# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

# Se escalan los resultados
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
    
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

  
model = XGBClassifier()
  
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
  
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_test, y_test, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision inicial: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

for i in delete:
    X_new=np.delete(X,[i], axis=1)
    # Se separa el trainig set y el test set 
    X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y, test_size=0.33, random_state=1)

    # Se escalan los resultados
    scaler = MinMaxScaler()
    scaler.fit(X_train_new)
    X_train_new = scaler.transform(X_train_new)
    X_test_new = scaler.transform(X_test_new)
      
    X_train_new = pd.DataFrame(X_train_new)
    X_test_new = pd.DataFrame(X_test_new)

    model = XGBClassifier()
    
    model.fit(X_train_new, y_train_new)
    y_pred_new=model.predict(X_test_new)
    
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    n_scores = cross_val_score(model, X_test_new, y_test_new, scoring='accuracy', cv=cv, n_jobs=-1)
    print(f'Precision sin la(s) variable(s) {i}: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

"""Así pues, se puede observar como al quitar las variables con menos dependencia la precisión mejora en algunos casos, así que se podrían eliminar.
En este caso, **la mejor precisión se obtiene al eliminar la columna 12**, con una precisión del 83.1% y un varianza del 0.043.

### Numéricas

#### Coeficiente de correlación ANOVA

Cuanto mayor sea el coeficiente mayor será la correlación. Columnas más correladas: 28, 30 y 31.
"""

# Funcion para seleccionar las variables
def select_features(X_train, y_train, X_test):
    # Configuramos el selector a todas las variables
    fs = SelectKBest(score_func=f_classif, k='all')
    # Entrenamos el selector sobre el conjunto de train
    fs.fit(X_train, y_train)
    # Transformamos los datos de entrenamiento
    X_train_fs = fs.transform(X_train)
    # Transformamos los datos de test
    X_test_fs = fs.transform(X_test)
    return X_train_fs, X_test_fs, fs

def scaler_function(X_train,X_test):
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    X_train = pd.DataFrame(X_train)
    X_test= pd.DataFrame(X_test)
    return X_train,X_test

# Realizamos el cálculo solo en las variables numericas
X_num = X_numerical.to_numpy()[:, :-1]
y = X_all.to_numpy()[:, -1]

# Dividimos train y test
X_train_num, X_test_num, y_train_num, y_test_num = train_test_split(X_num, y, test_size=0.33, random_state=1)

# Escalamos los datos
X_train_num, X_test_num = scaler_function(X_train_num, X_test_num)

# Seleccionamos las variables
X_train_fs, X_test_fs, fs = select_features(X_train_num, y_train_num, X_test_num)

# Imprimimos la puntuacion de las variables
for i in range(len(fs.scores_)):
    print('Feature {}: {}'.format(i, fs.scores_[i]))
# Dibujamos la puntuación
pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
pyplot.show()

"""####Precisión al eliminar variables

Vamos a eliminar las columnas con valores más bajos de correlación según el coeficiente de correlación Anova. Se han elegido las 3 columnas con valores más bajos, estas columnas son la 17, 23 y 32. Se ha mirado la precisión obtenida al eliminar estas columnas únicamente, y una combinación de las mismas. Finalmente, se ha obtenido un valor de precisión más alto al eliminar las 3 columnas juntas, siendo esta precisión de 83.3%, con una varianza de 0,043. En el caso de eliminar la columna 17 y la 23 por separado, las precisiones obtenidas difieren en una décima, es decir, una precisión de 83.2, pero con una varianza mayor, y en el caso de eliminar las 6 columnas con valores más bajos juntas, se obtiene una precisión también del 83.3%, pero la varianza también es mayor.

**Por lo tanto, finalmente se escogería eliminar las columnas 17, 23 y 32 conjuntamente.**
"""

indextodelete = [17,23,32, [17,23], [17,32], [23,32], [17,23,32], [17,18,20,23,24,32]]
# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]

# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)

X_num = X_numerical.to_numpy()[:, :-1]
y = X_all.to_numpy()[:, -1]


for i in indextodelete:
    X_new=np.delete(X,[i], axis=1)
    # Se separa el trainig set y el test set 
    X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y, test_size=0.33, random_state=1)

    # Se escalan los resultados
    scaler = MinMaxScaler()
    scaler.fit(X_train_new)
    X_train_new = scaler.transform(X_train_new)
    X_test_new = scaler.transform(X_test_new)
    
    X_train_new = pd.DataFrame(X_train_new)
    X_test_new = pd.DataFrame(X_test_new)

    model = XGBClassifier()
  
    model.fit(X_train_new, y_train_new)
    y_pred_new=model.predict(X_test_new)
  
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    n_scores = cross_val_score(model, X_test_new, y_test_new, scoring='accuracy', cv=cv, n_jobs=-1)
    print(f'Precision sin la(s) variable(s) {i}: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

"""#### Con función de selección por información mutua

Se mide la dependencia entre las variables. Cuanto mayor sea el valor, mayor será la dependencia.
Columnas con valores más altos: 22 y 30.
"""

# Funcion para seleccionar las variables
def select_features(X_train, y_train, X_test):
    # Configuramos el selector a todas las variables
    fs = SelectKBest(score_func=mutual_info_regression, k='all')
    # Entrenamos el selector sobre el conjunto de train
    fs.fit(X_train, y_train)
    # Transformamos los datos de entrenamiento
    X_train_fs = fs.transform(X_train)
    # Transformamos los datos de test
    X_test_fs = fs.transform(X_test)
    return X_train_fs, X_test_fs, fs

# Realizamos el cálculo solo en las variables numericas
X_num = X_numerical.to_numpy()[:, :-1]
y = X_all.to_numpy()[:, -1]

# Dividimos train y test
X_train_num, X_test_num, y_train_num, y_test_num = train_test_split(X_num, y, test_size=0.33, random_state=1)

# Escalamos los datos
X_train_num, X_test_num = scaler_function(X_train_num, X_test_num)

# Seleccionamos las variables
X_train_fs, X_test_fs, fs = select_features(X_train_num, y_train_num, X_test_num)

# Imprimimos la puntuacion de las variables
for i in range(len(fs.scores_)):
    print('Feature {}: {}'.format(i, fs.scores_[i]))
# Dibujamos la puntuación
pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
pyplot.show()

"""####Precisión al eliminar variables

Vamos a eliminar las columnas con valores más bajos de correlación según la función de selección por información mutua. Se han elegido las 3 columnas con valores más bajos, estas columnas son la 21, 23 y 26. Se ha mirado la precisión obtenida al eliminar estas columnas únicamente, y una combinación de las mismas. También se ha evaluado la precisión al eliminar las 6 columnas con valores más bajos. Finalmente, se ha obtenido un valor de precisión más alto al eliminar las 6 columnas con valores más bajos, siendo esta precisión de 84.0%, con una varianza de 0.055. Seguidamente, en el caso de eliminar las columnas 21, 23 y 26, la precisión obtenida es de 83.7%, muy cercana a 84%, pero con una varianza menor, 0.048.

**Por lo tanto, finalmente la mejor opción sería eliminar las columnas 21, 23 y 26, que inicialmente son las columnas que dan un valor más bajo, 0.0.**
"""

indextodelete = [21, 23, 26, [21,23], [21,26], [23,26], [21,23,26], [21,23,26,27,28,32]]
# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]

# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)

X_num = X_numerical.to_numpy()[:, :-1]
y = X_all.to_numpy()[:, -1]


for i in indextodelete:
    X_new=np.delete(X,[i], axis=1)
    # Se separa el trainig set y el test set 
    X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y, test_size=0.33, random_state=1)

    # Se escalan los resultados
    scaler = MinMaxScaler()
    scaler.fit(X_train_new)
    X_train_new = scaler.transform(X_train_new)
    X_test_new = scaler.transform(X_test_new)
    
    X_train_new = pd.DataFrame(X_train_new)
    X_test_new = pd.DataFrame(X_test_new)

    model = XGBClassifier()
  
    model.fit(X_train_new, y_train_new)
    y_pred_new=model.predict(X_test_new)
  
    cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
    n_scores = cross_val_score(model, X_test_new, y_test_new, scoring='accuracy', cv=cv, n_jobs=-1)
    print(f'Precision sin la(s) variable(s) {i}: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')

"""##Importancia de variables

En esta parte se estudia la importancia de cada columna por separado dado un modelo específico. Esta será uno de los pilares del proyecto ya que de aquí escogeremos las columnas que utilizaremos más adelante y también el modelo. Estudiaremos las columnas más relevantes para los modelos de regresión logística, cart classifier, random forest classifier, xgb y método de permutación con repetición.

###Datos y funciones

Primero creamos un conjunto útil de funciones que usaremos en esta parte y cargamos los datos
"""

#Función que escala 
def scaler_function(X_train,X_test):
    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    X_train = pd.DataFrame(X_train)
    X_test= pd.DataFrame(X_test)
    return X_train,X_test

#Función que devuelve lista con las columnas menos importantes
def top_columns(top_number,scores,indexes,importance):
    #Lista ordenada de menor a mayor importancia
    sorted_scores=sorted(scores)

    importance_list= list(importance)
    #sorted_dictionary with key = order , value = importance number
    dictionary_scores= dict(zip(indexes,sorted_scores))
    new_importance_list= [abs(importance_list[i]) for i in range(len(importance_list))]

    top_columns_index=[]
    print(dictionary_scores)
    for key,value in dictionary_scores.items():
        if key< top_number: 
            previous_index=new_importance_list.index(value)
            print(f" Variable: { previous_index} Score: {importance_list[previous_index]} ")
            top_columns_index.append(previous_index)
        if new_importance_list[previous_index]==0:
            new_importance_list[previous_index]=0.00001

    print(top_columns_index)
    return top_columns_index

#Función que itera sobre un modelo y un conjunto de columnas especificas a quitar y un scoring_method 
def model_iterator(top_columns_index,model_given,scoring_method):
    #Iteramos quitando todas las columnas y viendo que pasa con cada eliminación
    top_columns_iterator=[]
    results_model=[]

    for i in top_columns_index:
        top_columns_iterator.append(i)
        print(f"Columnas eliminadas : {top_columns_iterator}")
        X_new=np.delete(X,top_columns_iterator, axis=1)
        # Se separa el trainig set y el test set 
        X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.33, random_state=1)
        # Se escalan los resultados
        X_train,X_test=scaler_function(X_train,X_test)
        #Apliquem un model
        model = model_given
        # Entrenem el model
        model.fit(X_train, y_train)
        y_pred=model.predict(X_test)
        #mirem la precisió
        cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
        n_scores = cross_val_score(model, X_test, y_test, scoring=scoring_method, cv=cv, n_jobs=-1)
        print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')
        results_model.append(n_scores)
        #Restauramos columnas
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

    # Se escalan los resultados
    X_train,X_test=scaler_function(X_train,X_test)
    return results_model


def ploting(results_model):
    # Dibujamos las bondad del modelo y el tiempo de ejecución para comparar
    labels_model=[i+1 for i in range (len(results_model))]
    pyplot.boxplot(results_model, labels=labels_model, showmeans=True)
    pyplot.show()

def ploting_all_scorings(scoring_list,top_columns_index):
    for i in range(len(scoring_list)):
        print(f"Scoring: {scoring_list[i]} \n")
        results_model=model_iterator(top_columns_index,model,scoring_list[i])
        ploting(results_model)

# Dividimos las variables independientes y la etiqueta
data = X_all.values
X, y = data[:, :-1], data[:, -1]
# Definimos el imputer
imputer = KNNImputer(n_neighbors = 3)
# Entrenamos sobre el dataset
imputer.fit(X)
# Transformamos el dataset
X = imputer.transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
#Se escalan los datos
X_train,X_test=scaler_function(X_train,X_test)

scoring_list=['accuracy','neg_log_loss','roc_auc']

"""Vamos a obtener las columnas más importantes para los métodos de regresión logística, decisiontreeclassifier, randomforest,xgbclassifier y permutación para clasificación. Una vez obtenidas las columnas,identificaremos las menos importantes y graficaremos la precisión en función de las columnas eliminadas.

###Regresión logística
"""

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot

scores=[]
indexes=[]
# Definimos el modelo
model = LogisticRegression()
# Entrenamos el modelo
model.fit(X_train, y_train)
# Vemos la importancia de cada variable
importance = model.coef_[0]

# Presentamos la importancia de cada variable
for i,v in enumerate(importance):
    print('Variable: {}, Score: {:.5f}'.format(i,v))
    scores.append(abs(v))
    indexes.append(i)

# Dibujamos la importancia para comparar visualmente
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

#Lista ordenada de menor a mayor importancia de columnas
top_number=28
top_columns_index=top_columns(top_number,scores,indexes,importance)

#Graficos con todos los scorings
ploting_all_scorings(scoring_list,top_columns_index)

"""###Cart Classification"""

from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
from matplotlib import pyplot
scores=[]
indexes=[]

# Definimos el modelo
model = DecisionTreeClassifier()
# Entrenamos el modelo
model.fit(X_train, y_train)
# Vemos la importancia de cada variable
importance = model.feature_importances_

# Presentamos la importancia de cada variable
for i,v in enumerate(importance):
    print('Variable: {}, Score: {:.5f}'.format(i,v))
    scores.append(abs(v))
    indexes.append(i)

# Dibujamos la importancia para comparar visualmente
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

#Lista ordenada de menor a mayor importancia
top_number=28
top_columns_index=top_columns(top_number,scores,indexes,importance)

#Graficos con todos los scorings
ploting_all_scorings(scoring_list,top_columns_index)

"""###Random Forest Classifier"""

from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from matplotlib import pyplot
scores=[]
indexes=[]
# Definimos el modelo
model = RandomForestClassifier()
# Entrenamos el modelo
model.fit(X_train, y_train)
# Vemos la importancia de cada variable
importance = model.feature_importances_
# Presentamos la importancia de cada variable
for i,v in enumerate(importance):
    print('Variable: {}, Score: {:.5f}'.format(i,v))
    scores.append(abs(v))
    indexes.append(i)
# Dibujamos la importancia para comparar visualmente
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

#Lista ordenada de menor a mayor importancia de columnas
top_number=28
top_columns_index=top_columns(top_number,scores,indexes,importance)
remaining_columns_forest=[i for i in range (len(importance)) if i not in top_columns_index]

#Graficos con todos los scorings
ploting_all_scorings(scoring_list,top_columns_index)

"""###XGB"""

from sklearn.datasets import make_classification
from xgboost import XGBClassifier
from matplotlib import pyplot
scores=[]
indexes=[]

# Definimos el modelo
model = XGBClassifier()
# Entrenamos el modelo
model.fit(X_train, y_train)
# Vemos la importancia de cada variable
importance = model.feature_importances_

# Presentamos la importancia de cada variable
for i,v in enumerate(importance):
    print('Variable: {}, Score: {:.5f}'.format(i,v))
    scores.append(abs(v))
    indexes.append(i)

# Dibujamos la importancia para comparar visualmente
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

#Lista ordenada de menor a mayor importancia
top_number=28
top_columns_index_xgb=top_columns(top_number,scores,indexes,importance)

#Graficos con todos los scorings
ploting_all_scorings(scoring_list,top_columns_index_xgb)

top_columns_index_xgb.pop()
top_columns_index_xgb.pop()
top_columns_index_xgb.pop()
print(top_columns_index_xgb)

"""###Permutación para clasificación"""

from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.inspection import permutation_importance
from matplotlib import pyplot
scores=[]
indexes=[]

# Definimos el modelo
model = KNeighborsClassifier()
# Entrenamos el modelo
model.fit(X_train, y_train)
# Definimos la funcion de permutacion
results = permutation_importance(model, X_train, y_train, scoring='accuracy')
# Vemos la importancia de cada variable
importance = results.importances_mean
# Presentamos la importancia de cada variable
for i,v in enumerate(importance):
    print('Variable: {}, Score: {:.5f}'.format(i,v))
    scores.append(abs(v))
    indexes.append(i)
# Dibujamos la importancia para comparar visualmente
pyplot.bar([x for x in range(len(importance))], importance)
pyplot.show()

#Lista ordenada de menor a mayor importancia de columnas
top_number=28
top_columns_index=top_columns(top_number,scores,indexes,importance)

#Graficos con todos los scorings
ploting_all_scorings(scoring_list,top_columns_index)

"""###Comparación de resultados

En nuestro caso particular los mejores resultados son los que vienen dados cuando se usa un XGboost y se eliminan las columnas 7, 25, 27, 19, 1, 23, 20, 21, 12, 32, 22, 28, 4. Se obtiene una precisión del (85.7% ± 0.039%)

## Modelos

###XGBoost

Dado que el método que más precisión nos dió en la sección de antes fue el de XGB, es ese el que utilizaremos para nuestro análisis y también será este el modelo que afinaremos.

####Modelo con selección de variables y sin afinar

Sin afinar el modelo se puede observar que para las columnas seleccionadas en la sección anterior se obtiene una precisión en las predicciones del 85.5 % en el conjunto de test.
"""

from xgboost import XGBClassifier

X_new=np.delete(X,top_columns_index_xgb, axis=1)
# Se separa el trainig set y el test set 
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=1)
# Se escalan los resultados
X_train,X_test=scaler_function(X_train,X_test)
#Apliquem un model
model = XGBClassifier()
# Entrenem el model
model.fit(X_train, y_train)
y_pred=model.predict(X_test)
#mirem la precisió
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring=scoring_list[0], cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')
print('Accuracy {} %'.format(100*accuracy_score(y_test, y_pred)))

a=pd.DataFrame(X_train)
a

"""####Optimización de hiperparámetros

Vamos a optimizar los hiperparámetros usando un GridSearch y lo haremos en varias rondas para así tener un modelo más preciso donde después de cada ronda podamos reafinar los parámetros en función de los parámetros obtenidos previamente. Los parámetros que se han escogido para afinar son max_depth, learning_rate, gamma, reg_lambda, scale_pos_weight, subsample, colsample_bytree ya que hemos visto en varias fuentes que estos parámetros son relevantes para este modelo. En la tercera ronda también se afina el parámetro n_estimators. Los valores de los parámetros se han escogido basándose en https://towardsdatascience.com/beginners-guide-to-xgboost-for-classification-problems-50f75aac5390

#####Primera ronda
"""

from sklearn.model_selection import GridSearchCV

parameters = {
    "max_depth": [3, 4, 5, 7],
    "learning_rate": [0.1, 0.01, 0.05,0.001],
    "gamma": [0, 0.25,0.5,1],
    "reg_lambda": [0, 1, 10],
    "scale_pos_weight": [1, 3, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.5],
}

        
grid_search = GridSearchCV(estimator = model,
                           param_grid = parameters, 
                           scoring = 'accuracy',
                           cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1),
                           n_jobs = -1)

grid_search = grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_

best_parameters = grid_search.best_params_

print(best_accuracy)
print(best_parameters)
print(grid_search.score(X_train, y_train))

from xgboost import XGBClassifier
#Apliquem el XGBoostClassifier
model = XGBClassifier(colsample_bytree=0.5,gamma=0.5,learning_rate=0.05,max_depth=3,reg_lambda=10,scale_pos_weight=3,subsample=0.8)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')
print('Accuracy {} %'.format(100*accuracy_score(y_test, y_pred)))

"""#####Segunda ronda"""

from sklearn.model_selection import GridSearchCV
#Volvemos a afinar el modelo
parameters = {
    "max_depth": [3, 4],
    "learning_rate": [0.08, 0.05, 0.03,0.01],
    "gamma": [0.3,0.5,0.7,0.9,1.5],
    "reg_lambda": [ 10,20,50],
    "scale_pos_weight": [3, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.5],
}

              
grid_search = GridSearchCV(estimator = model,
                           param_grid = parameters, 
                           scoring = 'accuracy',
                           cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1),
                           n_jobs = -1)

grid_search = grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_

best_parameters = grid_search.best_params_

print(best_accuracy)
print(best_parameters)
print(grid_search.score(X_train, y_train))

from xgboost import XGBClassifier
#Apliquem el XGBoostClassifier
model = XGBClassifier(colsample_bytree=0.5,gamma=0.3,learning_rate=0.05,max_depth=3,reg_lambda=20,scale_pos_weight=3,subsample=0.8)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')
print('Accuracy {} %'.format(100*accuracy_score(y_test, y_pred)))

"""#####Tercera ronda"""

from sklearn.model_selection import GridSearchCV
#Volvemos a afinar el modelo
parameters = {
    "max_depth": [3, 4],
    "learning_rate": [0.08, 0.05, 0.03,0.01],
    "gamma": [0.1,0.2,0.3,0.5],
    "reg_lambda": [ 15,20,30],
    "scale_pos_weight": [2,3, 5],
    "subsample": [0.8],
    "colsample_bytree": [0.5],
    "n_estimators":[75,100,150]
}

              
grid_search = GridSearchCV(estimator = model,
                           param_grid = parameters, 
                           scoring = 'accuracy',
                           cv = RepeatedStratifiedKFold(n_splits=3, n_repeats=3, random_state=1),
                           n_jobs = -1)

grid_search = grid_search.fit(X_train, y_train)

best_accuracy = grid_search.best_score_

best_parameters = grid_search.best_params_

print(best_accuracy)
print(best_parameters)
print(grid_search.score(X_train, y_train))

from xgboost import XGBClassifier
#Apliquem el XGBoostClassifier
model = XGBClassifier(colsample_bytree=0.5,gamma=0.2,learning_rate=0.03,max_depth=3,reg_lambda=15,scale_pos_weight=3,subsample=0.8,n_estimators=150)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1)
print(f'Precision: {np.mean(n_scores):.3f} ({np.std(n_scores):.3f})')
print('Accuracy {} %'.format(100*accuracy_score(y_test, y_pred)))

"""####Conclusiones y resultados

Después de la tercera ronda de afinamiento, se ha decidido desistir de afinar más ya que no se observa una mejoría en la precisión del modelo. Por lo tanto, los resultados finales con los mejores parámetros son :
'colsample_bytree': 0.5, 'gamma': 0.2, 'learning_rate': 0.03, 'max_depth': 3, 'n_estimators': 150, 'reg_lambda': 15, 'scale_pos_weight': 3, 'subsample': 0.8 .
Usando estos parámetros se obtiene una precisión de un 89% en el conjunto de test.

##Modelo Deep Learning

En esta última parte vamos a crear un modelo que use redes neuronales para hacer las predicciones. Para ello, primero importaremos Keras y las librerias necesarias, luego inicializaremos la red neuronal, añadiremos las capas necesarias, ajustaremos el modelo a nuestro conjunto X_train y finalmente evaluaremos el modelo y veremos que tan preciso es.

###Carga de las librerias y incialización de la RNA
"""

import keras
from keras.models import Sequential
from keras.layers import Dense

a=pd.DataFrame(X_train)
a

classifier = Sequential()

classifier.add(Dense(units = 11, kernel_initializer = "uniform",  
                     activation = "relu", input_dim = 20))

"""###Adición de capas ocultas y capa de salida

Se ha escogido como función de activación en la capa final la función sigmoide ya que esta es adecuada para una clasificación binaria y porque se puede interpretar como una probabilidad entre 0 y 1 de que un cliente cometa fraude. Luego en la evaluación del modelo se ha establecido un umbral de 0.5 de manera que si el resultado devuelto por la neurona de la capa final es mayor que 0.5 entonces el output será 1 y 0 en caso de ser menor que 0.5.  
"""

classifier.add(Dense(units = 11, kernel_initializer = "uniform",  activation = "relu"))

classifier.add(Dense(units = 1, kernel_initializer = "uniform",  activation = "sigmoid"))

"""###Compilación de la RNA y ajuste al conjunto de entrenamiento"""

classifier.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

classifier.fit(X_train, y_train,  batch_size = 10, epochs = 100)

"""###Evaluación de los modelos y cálculo de predicciones finales

"""

y_pred  = classifier.predict(X_test)
y_pred = (y_pred>0.5)

from sklearn.metrics import confusion_matrix,classification_report
print('Accuracy {} %'.format(100*accuracy_score(y_test, y_pred)))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True)

print(classification_report(y_test, y_pred))

"""Al usar ANN, los mejores resultados son del 81% aproximadamente. Ese es el mejor resultado que se ha obtenido. Se ha comprobado que si se intenta entrenar más al modelo este se ajusta mejor a los datos de entrenamiento pero no se ajusta tan bien a los de test debido al overfitting. Haría falta un estudio más profundo y continuar variando diversos parámetros como el número de capas ,el número de neuronas en cada capa o la función de activación en cada capa para ver si se pueden obtener mejores resultados. 

Finalmente, si se compara la precisión de este método con el XGB se ve que el XGB es superior. Una posible causa es que para entrenar un modelo con redes neuronales, se necesita una gran cantidad de datos y en este caso particular el conjunto no es demasiado grande.
"""